name: CI
on:
  push:
    branches:
      - 'main'
jobs:
  my_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out our code
        uses: actions/checkout@v3
      - name: Percy test
        run: |
          npm run build-storybook
          PERCY_TOKEN=7278d9978205ebfd91cec019a21d8c1fe8fe9ac01a17e303df5fbf536c890a3c percy storybook ./storybook-static
