name: CI
on:
  push:
    branches:
      - 'main'
jobs:
  my_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out our code
        uses: actions/checkout@v3
      - name: Percy testing
        run: |
          npm install
          npm run build-storybook
          npx @percy/cli snapshot storybook-static/
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
